service: github-wc-webhook

provider:
  name: aws
  runtime: nodejs4.3
  stage: ${file(config.json):STAGE}
  region: ${file(config.json):REGION}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:*"
      Resource: "arn:aws:dynamodb:*:*:table/${file(config.json):TABLE_NAME}"

functions:
  webhook:
    handler: handlers/webhook.handle
    events:
      - http:
          path: /webhook
          method: post
  commits:
    handler: handlers/commits.handle
    events:
      - http:
          path: /commits
          method: get

resources:
  Resources:
    DynamoDbTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${file(config.json):TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
